version: '3.9'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data

  test-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  test-jaeger:
    image: jaegertracing/all-in-one:1.51
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - '16687:16686' # Jaeger UI for tests
      - '4319:4317'   # OTLP gRPC for tests
      - '4320:4318'   # OTLP HTTP for tests